---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'foundation'
SiteConfig:
  extensions:
    - SiteConfigExtension
Director:
  enviroment_type: 'dev'
Debug:
  friendly_error_httpcode: true
Image:
  extensions:
    - GalleryImage
    - WebGalleryImage
#    - AwardImage
    - AdFilesExtension
File:
  allowed_extensions:
    - html